<?php
if (function_exists('acf_add_local_field_group')):

    /** **************************************************************************************************
     * Taxonomy
     * カテゴリーカスタムフィールド
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_61666bee9334c',
        'title'  => 'カテゴリーカスタムフィールド',
        'fields' => array(
            array(
                'key'               => 'field_61666c4ba7a9f',
                'label'             => 'カラー設定',
                'name'              => 'カラー設定',
                'type'              => 'radio',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    'hex'      => 'HEX値',
                    'bs_class' => 'Bootstrapクラス',
                ),
                'allow_null'        => 0,
                'other_choice'      => 0,
                'default_value'     => 'hex',
                'layout'            => 'horizontal',
                'return_format'     => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key'               => 'field_61666c00a7a9e',
                'label'             => 'HEX値',
                'name'              => 'HEX値',
                'type'              => 'color_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_61666c4ba7a9f',
                            'operator' => '==',
                            'value'    => 'hex',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'default_value'  => '',
                'enable_opacity' => 0,
                'return_format'  => 'string',
            ),
            array(
                'key'               => 'field_61666d0da7aa3',
                'label'             => 'Bootstrapクラス',
                'name'              => 'Bootstrapクラス',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_61666c4ba7a9f',
                            'operator' => '==',
                            'value'    => 'bs_class',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    'primary'   => 'primary',
                    'secondary' => 'secondary',
                    'success'   => 'success',
                    'info'      => 'info',
                    'warning'   => 'warning',
                    'danger'    => 'danger',
                    'light'     => 'light',
                    'dark'      => 'dark',
                ),
                'default_value' => false,
                'allow_null'    => 0,
                'multiple'      => 0,
                'ui'            => 0,
                'return_format' => 'value',
                'ajax'          => 0,
                'placeholder'   => '',
            ),
            array(
                'key'               => 'field_61669be712565',
                'label'             => '表示順',
                'name'              => '表示順',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => 0,
                'max'           => '',
                'step'          => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'header_category',
                ),
            ),
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'cat_services',
                ),
            ),
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'cat_events',
                ),
            ),
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'cat_coupon',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ));


    /** **************************************************************************************************
     * Taxonomy
     * 市町村
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_61fc8d167b0ad',
        'title'  => '市町村',
        'fields' => array(
            array(
                'key'               => 'field_61fc8d216af40',
                'label'             => '人口',
                'name'              => 'population',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 0,
                'edit_in_rest'         => 0,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'min'                  => 0,
                'max'                  => '',
                'step'                 => '',
                'show_column'          => 1,
                'show_column_sortable' => 1,
                'show_column_weight'   => 100,
                'allow_quickedit'      => 1,
                'allow_bulkedit'       => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'cities',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ));


    /** **************************************************************************************************
     * イベント情報
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_616fc20d2e027',
        'title'  => 'イベント情報',
        'fields' => array(
            array(
                'key'               => 'field_616fc20d34aaf',
                'label'             => '事業所ID（WPユーザーID）',
                'name'              => '事業所id',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_6189d0285544d',
                'label'             => 'ギャラリー',
                'name'              => 'ギャラリー',
                'type'              => 'gallery',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'return_format' => 'array',
                'preview_size'  => 'medium',
                'insert'        => 'append',
                'library'       => 'all',
                'min'           => '',
                'max'           => '',
                'min_width'     => '',
                'min_height'    => '',
                'min_size'      => '',
                'max_width'     => '',
                'max_height'    => '',
                'max_size'      => '',
                'mime_types'    => '',
            ),
            array(
                'key'               => 'field_6189c30547451',
                'label'             => '主催',
                'name'              => '主催',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_6189c31147452',
                'label'             => '協賛',
                'name'              => '協賛',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_618a24fb2b3cf',
                'label'             => '開催日（自）',
                'name'              => '開催日_自_',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'Y-m-d',
                'return_format'  => 'Y-m-d',
                'first_day'      => 1,
            ),
            array(
                'key'               => 'field_618a25222b3d0',
                'label'             => '開催日（至）',
                'name'              => '開催日_至_',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'Y-m-d',
                'return_format'  => 'Y-m-d',
                'first_day'      => 1,
            ),
            array(
                'key'               => 'field_618a25362b3d1',
                'label'             => '開催時間（自）',
                'name'              => '開催時間_自_',
                'type'              => 'time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'H:i',
                'return_format'  => 'H:i',
            ),
            array(
                'key'               => 'field_618a255e2b3d2',
                'label'             => '開催時間（至）',
                'name'              => '開催時間_至_',
                'type'              => 'time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'H:i',
                'return_format'  => 'H:i',
            ),
            array(
                'key'               => 'field_6189be904744c',
                'label'             => '開催日時詳細',
                'name'              => '開催日時詳細',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_616fc4acd447a',
                'label'             => '開催地',
                'name'              => '開催地',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6189bf6a4744f',
                'label'             => '開催地住所',
                'name'              => '開催地住所',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6189be464744a',
                'label'             => '交通アクセス',
                'name'              => '交通アクセス',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_618c788be7cef',
                'label'             => '定員',
                'name'              => '定員',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_6189be634744b',
                'label'             => 'お問い合わせ',
                'name'              => 'お問い合わせ',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_6184cc1cb7e56',
                'label'             => '特設サイト',
                'name'              => '特設サイト',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
            ),
            array(
                'key'               => 'field_616fc20d34ae7',
                'label'             => '詳細',
                'name'              => '詳細',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'tabs'          => 'all',
                'toolbar'       => 'full',
                'media_upload'  => 0,
                'delay'         => 0,
            ),
            array(
                'key'               => 'field_6189bea94744d',
                'label'             => '料金',
                'name'              => '料金',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_6189beef4744e',
                'label'             => '備考',
                'name'              => '備考',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'events',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'acf_after_title',
        'style'                 => 'seamless',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => array(
            'permalink',
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ),
        'active'      => true,
        'description' => '',
    ));


    /** **************************************************************************************************
     * クーポン
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_618877b04dbfd',
        'title'  => 'クーポン',
        'fields' => array(
            array(
                'key'               => 'field_618877ba5f1f2',
                'label'             => 'レコード番号',
                'name'              => 'レコード番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 1,
                'edit_in_rest'         => 1,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'min'                  => '',
                'max'                  => '',
                'step'                 => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_6188ded62f849',
                'label'             => '利用開始日',
                'name'              => '利用開始日',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 1,
                'edit_in_rest'         => 1,
                'display_format'       => 'Y-m-d',
                'return_format'        => 'Y-m-d',
                'first_day'            => 1,
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_6204a0bb69de5',
                'label'             => '利用終了日',
                'name'              => '利用終了日',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 1,
                'edit_in_rest'         => 1,
                'display_format'       => 'Y-m-d',
                'return_format'        => 'Y-m-d',
                'first_day'            => 1,
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_62047949e5fda',
                'label'             => '事業者情報',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_62047999e5fdd',
                'label'             => '事業所レコード番号',
                'name'              => '事業所レコード番号',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 0,
                'edit_in_rest'         => 0,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'maxlength'            => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_6204797ee5fdc',
                'label'             => '事業所名',
                'name'              => '事業所名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 0,
                'edit_in_rest'         => 0,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'maxlength'            => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_620479c0e5fde',
                'label'             => '郵便番号',
                'name'              => '郵便番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_620479d2e5fdf',
                'label'             => '都道府県名',
                'name'              => '都道府県名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 0,
                'edit_in_rest'         => 0,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'maxlength'            => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_62047a57e5fe1',
                'label'             => '住所',
                'name'              => '住所',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 0,
                'edit_in_rest'         => 0,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'maxlength'            => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_62047a60e5fe2',
                'label'             => '電話番号',
                'name'              => '電話番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_62047960e5fdb',
                'label'             => 'クーポン詳細',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_6193045983a31',
                'label'             => '定価',
                'name'              => '定価',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 1,
                'edit_in_rest'         => 1,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '円',
                'min'                  => '',
                'max'                  => '',
                'step'                 => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_6193056a83a35',
                'label'             => '割引値',
                'name'              => '割引値',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_6193052c83a34',
                'label'             => '割引種別',
                'name'              => '割引種別',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    '円引' => '円引',
                    '％引' => '％引',
                ),
                'default_value' => false,
                'allow_null'    => 0,
                'multiple'      => 0,
                'ui'            => 0,
                'return_format' => 'value',
                'ajax'          => 0,
                'placeholder'   => '',
            ),
            array(
                'key'               => 'field_61936bcf18849',
                'label'             => '店舗名',
                'name'              => '店舗名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6194a2ffc002b',
                'label'             => '条件',
                'name'              => '条件',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6194a312c002c',
                'label'             => '条件詳細',
                'name'              => '条件詳細',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'coupons',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => array(
            'permalink',
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ),
        'active'      => true,
        'description' => '',
    ));


    /** **************************************************************************************************
     * 事業所情報
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_6139c86bd9b08',
        'title'  => '事業所情報',
        'fields' => array(
            array(
                'key'               => 'field_616d1342bcb28',
                'label'             => 'ページテンプレート',
                'name'              => 'ページテンプレート',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'choices'      => array(
                    'a' => 'パターンA',
                    'b' => 'パターンB',
                    'c' => 'パターンC',
                ),
                'default_value' => 'a',
                'allow_null'    => 0,
                'multiple'      => 0,
                'ui'            => 0,
                'return_format' => 'value',
                'ajax'          => 0,
                'placeholder'   => '',
            ),
            array(
                'key'               => 'field_6139c8d422beb',
                'label'             => '事業所ID（WPユーザーID）',
                'name'              => '事業所id',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_6139c92e22bec',
                'label'             => '概要',
                'name'              => '概要',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'tabs'          => 'all',
                'toolbar'       => 'full',
                'media_upload'  => 0,
                'delay'         => 0,
            ),
            array(
                'key'               => 'field_62006d4362fd6',
                'label'             => '検索キーワード',
                'name'              => '検索キーワード',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'enterprises',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'acf_after_title',
        'style'                 => 'seamless',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => array(
            'the_content',
            'permalink',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'categories',
            'tags',
            'send-trackbacks',
        ),
        'active'      => true,
        'description' => '',
    ));


    /** **************************************************************************************************
     * 基本情報
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_614967bbadd6c',
        'title'  => '基本情報',
        'fields' => array(
            array(
                'key'               => 'field_614d309fbc677',
                'label'             => 'rec_id',
                'name'              => 'rec_id',
                'type'              => 'number',
                'instructions'      => 'kintone事業所レコード番号',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_614967d216409',
                'label'             => '事業所名',
                'name'              => '事業所名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_614967ec1640a',
                'label'             => '事業所名_ふりがな_',
                'name'              => '事業所名_ふりがな_',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_614967f71640b',
                'label'             => '担当者名',
                'name'              => '担当者名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149680a1640c',
                'label'             => '担当者メールアドレス',
                'name'              => 'メールアドレス_担当者_',
                'type'              => 'email',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key'               => 'field_6149681b1640d',
                'label'             => '郵便番号',
                'name'              => '郵便番号',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149682b1640e',
                'label'             => '都道府県名',
                'name'              => '都道府県名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149683d1640f',
                'label'             => '住所1(市区町村名)',
                'name'              => '住所1_市名_',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149684416410',
                'label'             => '住所2',
                'name'              => '住所2',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149684916411',
                'label'             => 'URL',
                'name'              => 'サイトurl',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
            ),
            array(
                'key'               => 'field_6149685016412',
                'label'             => '電話番号',
                'name'              => '電話番号',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_6149687016413',
                'label'             => 'FAX',
                'name'              => 'fax',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61766a4950de9',
                'label'             => '外部リンクを使用',
                'name'              => '外部リンクを使用',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'message'       => '',
                'default_value' => 0,
                'ui'            => 0,
                'ui_on_text'    => '',
                'ui_off_text'   => '',
            ),
            array(
                'key'               => 'field_6188783ee6fba',
                'label'             => '求人規約承諾',
                'name'              => '求人規約承諾',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'message'       => '',
                'default_value' => 0,
                'ui'            => 0,
                'ui_on_text'    => '',
                'ui_off_text'   => '',
            ),
            array(
                'key'               => 'field_61e7728fbfbcc',
                'label'             => '緯度',
                'name'              => '緯度',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61e7729dbfbcd',
                'label'             => '経度',
                'name'              => '経度',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'current_user',
                    'operator' => '==',
                    'value'    => 'logged_in',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'page',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'post',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'job_offers',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'enterprises',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'events',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'servises',
                ),
                array(
                    'param'    => 'post_type',
                    'operator' => '!=',
                    'value'    => 'coupons',
                ),
            ),
            array(
                array(
                    'param'    => 'user_form',
                    'operator' => '==',
                    'value'    => 'edit',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'acf_after_title',
        'style'                 => 'seamless',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ));


    /** **************************************************************************************************
     * 求人情報
     ************************************************************************************************** */
    acf_add_local_field_group(array(
        'key'    => 'group_6139cbe9b994f',
        'title'  => '求人情報',
        'fields' => array(
            array(
                'key'               => 'field_61b946d1e604f',
                'label'             => 'レコード番号',
                'name'              => 'レコード番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_61f0a0c85994c',
                'label'             => '求人番号',
                'name'              => '求人番号',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61b854f80d720',
                'label'             => '掲載期限',
                'name'              => '掲載期限',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'Y-m-d',
                'return_format'  => 'Y-m-d',
                'first_day'      => 1,
            ),
            array(
                'key'               => 'field_61f0a0fe5994d',
                'label'             => '事業所情報',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_61f8b20efbdb8',
                'label'             => '事業所レコード番号',
                'name'              => '事業所レコード番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'         => 1,
                'edit_in_rest'         => 1,
                'default_value'        => '',
                'placeholder'          => '',
                'prepend'              => '',
                'append'               => '',
                'min'                  => '',
                'max'                  => '',
                'step'                 => '',
                'show_column'          => 0,
                'show_column_sortable' => 0,
                'show_column_weight'   => 1000,
                'allow_quickedit'      => 0,
                'allow_bulkedit'       => 0,
            ),
            array(
                'key'               => 'field_61f0a17a5994e',
                'label'             => '事業所名',
                'name'              => '事業所名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61f0a1c259950',
                'label'             => '郵便番号',
                'name'              => '郵便番号',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_61f0a1da59951',
                'label'             => '都道府県名',
                'name'              => '都道府県名',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61f0a1e759952',
                'label'             => '住所',
                'name'              => '住所',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61f0a1f259953',
                'label'             => '電話番号',
                'name'              => '電話番号',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61f0a20259954',
                'label'             => 'FAX',
                'name'              => 'FAX',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_61f0a1915994f',
                'label'             => '雇用情報',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_618371332c62a',
                'label'             => '就業場所',
                'name'              => '就業場所',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key'               => 'field_617b3cca39095',
                'label'             => '契約形態',
                'name'              => '契約形態',
                'type'              => 'radio',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    '正社員'       => '正社員',
                    '契約社員'      => '契約社員',
                    '派遣社員'      => '派遣社員',
                    'アルバイト・パート' => 'アルバイト・パート',
                    '日雇い'       => '日雇い',
                    '臨時（季節雇用）'  => '臨時（季節雇用）',
                    '請負'        => '請負',
                    '業務委託'      => '業務委託',
                    'その他の契約形態'  => 'その他の契約形態',
                ),
                'allow_null'        => 0,
                'other_choice'      => 0,
                'default_value'     => '',
                'layout'            => 'vertical',
                'return_format'     => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key'               => 'field_617f35f1d88d7',
                'label'             => '雇用開始日',
                'name'              => '雇用開始日',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 0,
                'display_format' => 'Y-m-d',
                'return_format'  => 'Y-m-d',
                'first_day'      => 1,
            ),
            array(
                'key'               => 'field_617f365ad88d8',
                'label'             => '雇用終了日',
                'name'              => '雇用終了日',
                'type'              => 'date_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 0,
                'display_format' => 'Y-m-d',
                'return_format'  => 'Y-m-d',
                'first_day'      => 1,
            ),
            array(
                'key'               => 'field_61b853b50d71f',
                'label'             => '募集人数',
                'name'              => '募集人数',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_61f0a31959955',
                'label'             => '待遇',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_617b3d6d39096',
                'label'             => '給与形態',
                'name'              => '給与形態',
                'type'              => 'radio',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    '年収' => '年収',
                    '月給' => '月給',
                    '日給' => '日給',
                    '時給' => '時給',
                ),
                'allow_null'        => 0,
                'other_choice'      => 0,
                'default_value'     => '',
                'layout'            => 'horizontal',
                'return_format'     => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key'               => 'field_617f3547d88d5',
                'label'             => '給与（自）',
                'name'              => '給与_自_',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '円',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_617f3585d88d6',
                'label'             => '給与（至）',
                'name'              => '給与_至_',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '円',
                'min'           => '',
                'max'           => '',
                'step'          => '',
            ),
            array(
                'key'               => 'field_61836ff5b70e7',
                'label'             => '給与補足',
                'name'              => '給与_補足',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a36c59956',
                'label'             => '福利厚生',
                'name'              => '福利厚生',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a37759957',
                'label'             => '勤務条件',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_61b856240d721',
                'label'             => '就労時間_自_',
                'name'              => '就労時間_自_',
                'type'              => 'time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'H:i',
                'return_format'  => 'H:i',
            ),
            array(
                'key'               => 'field_61837015b70e8',
                'label'             => '就労時間_至_',
                'name'              => '就労時間_至_',
                'type'              => 'time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'   => 1,
                'edit_in_rest'   => 1,
                'display_format' => 'H:i',
                'return_format'  => 'H:i',
            ),
            array(
                'key'               => 'field_61836fcab70e6',
                'label'             => '勤務時間補足',
                'name'              => '勤務時間_補足',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a3c659958',
                'label'             => '時間外労働の有無',
                'name'              => '時間外労働の有無',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'message'       => '',
                'default_value' => 1,
                'ui'            => 0,
                'ui_on_text'    => '',
                'ui_off_text'   => '',
            ),
            array(
                'key'               => 'field_61f0a44059959',
                'label'             => '時間外労働に関する補足説明',
                'name'              => '時間外労働に関する補足説明',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_617f335b3b3c0',
                'label'             => '勤務曜日',
                'name'              => '勤務曜日',
                'type'              => 'checkbox',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 1,
                'edit_in_rest' => 1,
                'choices'      => array(
                    '月' => '月',
                    '火' => '火',
                    '水' => '水',
                    '木' => '木',
                    '金' => '金',
                    '土' => '土',
                    '日' => '日',
                ),
                'allow_custom'  => 0,
                'default_value' => array(),
                'layout'        => 'horizontal',
                'toggle'        => 0,
                'return_format' => 'value',
                'save_custom'   => 0,
            ),
            array(
                'key'               => 'field_61f0a46f5995a',
                'label'             => '勤務曜日に関する補足説明',
                'name'              => '勤務曜日に関する補足説明',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61836f8cb70e5',
                'label'             => '休日に関する補足説明',
                'name'              => '休日に関する補足説明',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a4995995b',
                'label'             => '仕事に関する記載事項',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_6139cbe9bb997',
                'label'             => '仕事内容',
                'name'              => '仕事内容',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'tabs'          => 'all',
                'toolbar'       => 'full',
                'media_upload'  => 0,
                'delay'         => 0,
            ),
            array(
                'key'               => 'field_61f0a4b15995c',
                'label'             => '必須条件',
                'name'              => '必須条件',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a4c05995d',
                'label'             => '優遇条件',
                'name'              => '優遇条件',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a4d25995e',
                'label'             => '仕事に関する記載事項',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest' => 0,
                'edit_in_rest' => 0,
                'placement'    => 'top',
                'endpoint'     => 0,
            ),
            array(
                'key'               => 'field_617f33dd3b3c1',
                'label'             => '採用担当者からのコメント',
                'name'              => '採用担当者からのコメント',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 1,
                'edit_in_rest'  => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a5b35995f',
                'label'             => '採用担当者',
                'name'              => '採用担当者',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a5cb59960',
                'label'             => '応募情報',
                'name'              => '応募情報',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'new_lines'     => '',
            ),
            array(
                'key'               => 'field_61f0a62359961',
                'label'             => '問い合わせ先',
                'name'              => '問い合わせ先',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'show_in_rest'  => 0,
                'edit_in_rest'  => 0,
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'job_offers',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'acf_after_title',
        'style'                 => 'seamless',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => array(
            'permalink',
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ),
        'active'      => true,
        'description' => '',
    ));

endif;
